<a href="https://colab.research.google.com/github/Pangoa1992/PRACTICA-WILLY/blob/main/EXAMEN%20PRACTICO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Parte 1: Fundamentos NumPy

1. Crea un arreglo NumPy de dimensión 1 con los números del 1 al 20

In [ ]:
import numpy as np

arr = np.arange(1, 21)
print("Arreglo 1D (1-20):", arr)


Arreglo 1D (1-20): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Selecciona los múltiplos de 3 de ese arreglo y muéstralos.

In [ ]:
multiplos_3 = arr[arr % 3 == 0]
print("Múltiplos de 3:", multiplos_3)


Múltiplos de 3: [ 3  6  9 12 15 18]


3. Genera una matriz aleatoria de tamaño 5x5 con números entre 0 y 1

In [ ]:
np.random.seed(0)  # semilla para que siempre salga igual
mat = np.random.rand(5,5)
print("Matriz 5x5 aleatoria:\n", mat)


Matriz 5x5 aleatoria:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]


4. Calcula la media, la desviación estándar y el valor máximo de esa matriz.

In [ ]:
print("Media:", mat.mean())
print("Desviación estándar:", mat.std())
print("Valor máximo:", mat.max())


Media: 0.5907662544523903
Desviación estándar: 0.2824260166721418
Valor máximo: 0.978618342232764


5. Transforma la matriz en un vector de una sola dimensión

In [ ]:
mat_vector = mat.ravel()
print("Matriz convertida en vector 1D:", mat_vector)


Matriz convertida en vector 1D: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443]


Parte 2: Fundamentos Pandas

1. Crea un DataFrame con los siguientes datos de estudiantes:
Nombre Edad Nota_Matemáticas Nota_IA
Ana
20
18
Luis
17
21
15
María
14
19
16
Pedro
18
22
12
Sofía
13
20
19
20

In [ ]:
import pandas as pd

data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}
df = pd.DataFrame(data)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20


2. Calcula el promedio de cada columna numérica.

In [ ]:
print(df.select_dtypes(include=[np.number]).mean())


Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


3. Filtra los estudiantes con nota de IA mayor a 15.

In [ ]:
print(df[df["Nota_IA"] > 15])


  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20


4. Agrega una nueva columna llamada Promedio que contenga el promedio de
Nota_Matemáticas y Nota_IA.

In [ ]:
df["Promedio"] = df[["Nota_Matemáticas", "Nota_IA"]].mean(axis=1)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


5. Ordena el DataFrame según la columna Promedio de mayor a menor.

In [ ]:
print(df.sort_values(by="Promedio", ascending=False))


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5


Parte 3: Algoritmia aplicada

1. Escribe una función en Python que reciba una lista de números y devuelva:
o El número mayor
o El número menor
o El promedio

In [ ]:
def stats_list(nums):
    arr = np.array(nums, dtype=float)
    return arr.max(), arr.min(), arr.mean()

ejemplo = [3, 7, 1, 9, 4]
print("Mayor, menor y promedio:", stats_list(ejemplo))


Mayor, menor y promedio: (np.float64(9.0), np.float64(1.0), np.float64(4.8))


2. Usando NumPy, implementa una función de activación Sigmoide definida como:
f(x)=11+e−xf(x) = \frac{1}{1 + e^{-x}}f(x)=1+e−x1  
Aplica la función a un arreglo x = np.array([-2, -1, 0, 1, 2]).

In [ ]:
def sigmoid(x):
    x = np.array(x, dtype=float)
    return 1 / (1 + np.exp(-x))

x = np.array([-2, -1, 0, 1, 2])
print("Sigmoide aplicada:", sigmoid(x))


Sigmoide aplicada: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


3. Crea una función que clasifique a los estudiantes del DataFrame en "Aprobado"
si su Promedio ≥ 14, y "Desaprobado" en caso contrario. Añade una nueva
columna llamada Estado.

In [ ]:
def clasificar_estado(prom):
    return "Aprobado" if prom >= 14 else "Desaprobado"

df["Estado"] = df["Promedio"].apply(clasificar_estado)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado


Parte 4: Mini-proyecto

1. Agrega una nueva columna llamada Crecimiento que calcule el porcentaje de
crecimiento entre Ventas_2024 y Ventas_2025.

In [ ]:
ventas = pd.DataFrame({
    "Producto": ["A", "B", "C", "D", "E"],
    "Ventas_2024": [1000, 500, 0, 200, 800],
    "Ventas_2025": [1500, 450, 50, 400, 1600]
})

def crecimiento_pct(row):
    v2024, v2025 = row["Ventas_2024"], row["Ventas_2025"]
    if v2024 == 0:
        return np.inf if v2025 > 0 else 0.0
    return (v2025 - v2024) / v2024 * 100

ventas["Crecimiento"] = ventas.apply(crecimiento_pct, axis=1)
print(ventas)


  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A         1000         1500         50.0
1        B          500          450        -10.0
2        C            0           50          inf
3        D          200          400        100.0
4        E          800         1600        100.0


2. Identifica el producto con mayor crecimiento y muéstralo.

In [ ]:
print("Producto con mayor crecimiento:")
print(ventas.loc[ventas["Crecimiento"].idxmax()])


Producto con mayor crecimiento:
Producto         C
Ventas_2024      0
Ventas_2025     50
Crecimiento    inf
Name: 2, dtype: object


Parte 5: Resolución de ecuaciones

1. Ecuación de primer grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax+b=0ax + b = 0ax+b=0  
por ejemplo: 2x + 4 = 0.
o La función debe retornar el valor de x.

In [ ]:
def resolver_lineal(a, b):
    if a == 0:
        raise ValueError("a no puede ser 0 en ecuación lineal")
    return -b / a

print(resolver_lineal(2, 4))  # Ejemplo: 2x + 4 = 0


-2.0


2. Ecuación de segundo grado
o Implementa una función en Python que resuelva una ecuación de la forma:
ax2+bx+c=0ax^2 + bx + c = 0ax2+bx+c=0  
usando la fórmula general:
x=−b±b2−4ac2ax = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}x=2a−b±b2−4ac  
o La función debe retornar las dos soluciones (reales o complejas).

In [ ]:
import cmath

def resolver_cuadratica(a, b, c):
    if a == 0:
        if b == 0:
            raise ValueError("No es válida")
        return (-c / b,)
    disc = b**2 - 4*a*c
    sqrt_disc = cmath.sqrt(disc)
    x1 = (-b + sqrt_disc) / (2*a)
    x2 = (-b - sqrt_disc) / (2*a)
    return (x1, x2)

print(resolver_cuadratica(1, -5, 6))   # Ejemplo: x² - 5x + 6 = 0
print(resolver_cuadratica(1, 0, 1))    # Ejemplo: x² + 1 = 0


((3+0j), (2+0j))
(1j, -1j)
