<a href="https://colab.research.google.com/github/Pangoa1992/PRACTICA-WILLY/blob/main/Examen%20Practico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.arange(1, 21)
print("Arreglo 1D (1-20):", arr)


Arreglo 1D (1-20): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
multiplos_3 = arr[arr % 3 == 0]
print("Múltiplos de 3:", multiplos_3)


Múltiplos de 3: [ 3  6  9 12 15 18]


In [3]:
np.random.seed(0)  # semilla para que siempre salga igual
mat = np.random.rand(5,5)
print("Matriz 5x5 aleatoria:\n", mat)


Matriz 5x5 aleatoria:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]


In [7]:
print("Media:", mat.mean())
print("Desviación estándar:", mat.std())
print("Valor máximo:", mat.max())


Media: 0.5907662544523903
Desviación estándar: 0.2824260166721418
Valor máximo: 0.978618342232764


In [8]:
mat_vector = mat.ravel()
print("Matriz convertida en vector 1D:", mat_vector)


Matriz convertida en vector 1D: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443]


In [9]:
import pandas as pd

data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}
df = pd.DataFrame(data)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20


In [10]:
print(df.select_dtypes(include=[np.number]).mean())


Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


In [11]:
print(df[df["Nota_IA"] > 15])


  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20


In [12]:
df["Promedio"] = df[["Nota_Matemáticas", "Nota_IA"]].mean(axis=1)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


In [13]:
print(df.sort_values(by="Promedio", ascending=False))


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5


In [14]:
def stats_list(nums):
    arr = np.array(nums, dtype=float)
    return arr.max(), arr.min(), arr.mean()

ejemplo = [3, 7, 1, 9, 4]
print("Mayor, menor y promedio:", stats_list(ejemplo))


Mayor, menor y promedio: (np.float64(9.0), np.float64(1.0), np.float64(4.8))


In [15]:
def sigmoid(x):
    x = np.array(x, dtype=float)
    return 1 / (1 + np.exp(-x))

x = np.array([-2, -1, 0, 1, 2])
print("Sigmoide aplicada:", sigmoid(x))


Sigmoide aplicada: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [16]:
def clasificar_estado(prom):
    return "Aprobado" if prom >= 14 else "Desaprobado"

df["Estado"] = df["Promedio"].apply(clasificar_estado)
print(df)


  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado


In [17]:
ventas = pd.DataFrame({
    "Producto": ["A", "B", "C", "D", "E"],
    "Ventas_2024": [1000, 500, 0, 200, 800],
    "Ventas_2025": [1500, 450, 50, 400, 1600]
})

def crecimiento_pct(row):
    v2024, v2025 = row["Ventas_2024"], row["Ventas_2025"]
    if v2024 == 0:
        return np.inf if v2025 > 0 else 0.0
    return (v2025 - v2024) / v2024 * 100

ventas["Crecimiento"] = ventas.apply(crecimiento_pct, axis=1)
print(ventas)


  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A         1000         1500         50.0
1        B          500          450        -10.0
2        C            0           50          inf
3        D          200          400        100.0
4        E          800         1600        100.0


In [18]:
print("Producto con mayor crecimiento:")
print(ventas.loc[ventas["Crecimiento"].idxmax()])


Producto con mayor crecimiento:
Producto         C
Ventas_2024      0
Ventas_2025     50
Crecimiento    inf
Name: 2, dtype: object


In [19]:
def resolver_lineal(a, b):
    if a == 0:
        raise ValueError("a no puede ser 0 en ecuación lineal")
    return -b / a

print(resolver_lineal(2, 4))  # Ejemplo: 2x + 4 = 0


-2.0


In [20]:
import cmath

def resolver_cuadratica(a, b, c):
    if a == 0:
        if b == 0:
            raise ValueError("No es válida")
        return (-c / b,)
    disc = b**2 - 4*a*c
    sqrt_disc = cmath.sqrt(disc)
    x1 = (-b + sqrt_disc) / (2*a)
    x2 = (-b - sqrt_disc) / (2*a)
    return (x1, x2)

print(resolver_cuadratica(1, -5, 6))   # Ejemplo: x² - 5x + 6 = 0
print(resolver_cuadratica(1, 0, 1))    # Ejemplo: x² + 1 = 0


((3+0j), (2+0j))
(1j, -1j)
